id: P008036
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:57:02.291281
source_metadata:
  id: bdr:W1KG8583
  title: ལམ་རིམ་རྣམ་གྲོལ་ལག་བཅངས།
  author: ''
  volumes:
    58ca2a333ca249cb81ae129c0e3101e5:
      image_group_id: I1KG8597
      title: Volume 1 of lam rim rnam grol lag bcangs/
      volume_number: 1
      total_pages: 558
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
